{
  imports = [
    ./alacritty
    ./ashell
    ./base
    ./copyq
    ./eww
    ./fabric
    ./firefox
    ./fish
    ./gitnuro
    ./hyprland
    ./plymouth
    ./rofi
    ./sddm-sugar-candy
    ./starship
    ./swaylock-effects
    ./swaync
    ./zen-browser
    ./7d2d.nix
    ./bluetooth.nix
    ./devtools.nix
    ./discord.nix
    ./fastfetch.nix
    ./nautilus.nix
    ./nvidia.nix
    ./piper.nix
    ./playerctl.nix
    ./steam.nix
    ./cursor.nix
    ./zed.nix
    ./develnext.nix
    ./intellij.nix
    ./n8n.nix
    ./zerotier.nix
  ];
}
