{
  imports = [
    ./alacritty
    ./awesome
    ./base
    ./copyq
    ./eww
    ./firefox
    ./fish
    ./gitnuro
    ./hyprland
    ./jetbrains
    ./plymouth
    ./rofi
    ./sddm-sugar-candy
    ./starship
    ./swaylock-effects
    ./swaync
    ./zen-browser
    ./blocky.nix
    ./bluetooth.nix
    ./devtools.nix
    ./discord.nix
    ./fastfetch.nix
    ./nautilus.nix
    ./nvidia.nix
    ./onedrive.nix
    ./piper.nix
    ./playerctl.nix
    ./sops.nix
    ./steam.nix
    ./cursor.nix
  ];
}
